defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
          type: "posts"
        values:
          layout: "post"
plugins:
  - jekyll-minifier
jekyll-minifier:
  remove_intertag_spaces: true
